-- ============================================================================
-- RIVALEYE — BOOTSTRAP (auto-generated by scripts/build-bootstrap.sh)
-- Recreates the full database in a FRESH Supabase project.
--
-- HOW TO USE:
--   1. Create a new Supabase project.
--   2. Open SQL Editor → paste this whole file → Run.
--   3. Enable the 'vector' extension if the CREATE EXTENSION line errors
--      (Database → Extensions → enable 'vector'), then re-run from that line.
--   4. Auth → Providers: enable Email (magic link), Google, GitHub.
--
-- RUN ONCE on a blank project. Some statements use CREATE POLICY (not
-- idempotent) and will error if re-run on a populated database.
-- Generated: 2026-06-20T09:20:05Z
-- ============================================================================


-- ====================================================================== --
-- SOURCE: supabase/schema.sql
-- ====================================================================== --

-- ══════════════════════════════════════════════════════════════════════════════
-- RIVALEYE DATABASE SCHEMA
-- Run this in Supabase SQL Editor
-- ══════════════════════════════════════════════════════════════════════════════

-- ══════════════════════════════════════════════════════════════════════════════
-- USERS TABLE
-- ══════════════════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS users (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    email TEXT UNIQUE NOT NULL,
    
    -- Plan & Subscription
    plan TEXT DEFAULT 'free' CHECK (plan IN ('free', 'pro', 'enterprise')),
    dodo_customer_id TEXT,
    dodo_subscription_id TEXT,
    subscription_status TEXT DEFAULT 'none' CHECK (subscription_status IN ('none', 'active', 'cancelled', 'past_due')),
    
    -- Quota Tracking
    crawls_today INTEGER DEFAULT 0,
    manual_checks_today INTEGER DEFAULT 0,
    last_quota_reset TIMESTAMPTZ DEFAULT now(),
    settings JSONB DEFAULT '{
        "email_enabled": true,
        "digest_frequency": "instant",
        "slack_webhook_url": null
    }'::jsonb,
    
    created_at TIMESTAMPTZ DEFAULT now()
);

-- Index for auth lookups
CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);

-- ══════════════════════════════════════════════════════════════════════════════
-- COMPETITORS TABLE
-- ══════════════════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS competitors (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    
    name TEXT NOT NULL,
    url TEXT NOT NULL,
    status TEXT DEFAULT 'active' CHECK (status IN ('active', 'paused', 'error')),
    is_active BOOLEAN DEFAULT true,
    best_scraper TEXT CHECK (best_scraper IS NULL OR best_scraper IN ('firecrawl', 'playwright')),
    
    -- Tracking
    last_checked_at TIMESTAMPTZ,
    failure_count INTEGER DEFAULT 0,
    last_failure_at TIMESTAMPTZ,
    
    created_at TIMESTAMPTZ DEFAULT now()
);

-- Index for user lookups
CREATE INDEX IF NOT EXISTS idx_competitors_user_id ON competitors(user_id);
CREATE INDEX IF NOT EXISTS idx_competitors_status ON competitors(status);
CREATE INDEX IF NOT EXISTS idx_competitors_active ON competitors(is_active);

-- ══════════════════════════════════════════════════════════════════════════════
-- SNAPSHOTS TABLE
-- ══════════════════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS snapshots (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    competitor_id UUID NOT NULL REFERENCES competitors(id) ON DELETE CASCADE,
    
    hash TEXT NOT NULL,
    normalized_text TEXT NOT NULL,
    markdown TEXT,
    
    created_at TIMESTAMPTZ DEFAULT now()
);

-- Index for competitor lookups and hash deduplication
CREATE INDEX IF NOT EXISTS idx_snapshots_competitor_id ON snapshots(competitor_id);
CREATE INDEX IF NOT EXISTS idx_snapshots_hash ON snapshots(competitor_id, hash);
CREATE INDEX IF NOT EXISTS idx_snapshots_created_at ON snapshots(created_at);

-- ══════════════════════════════════════════════════════════════════════════════
-- ALERTS TABLE
-- ══════════════════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS alerts (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES users(id) ON DELETE CASCADE,
    competitor_id UUID NOT NULL REFERENCES competitors(id) ON DELETE CASCADE,
    
    diff_summary TEXT DEFAULT '',
    ai_insight JSONB DEFAULT '{}'::jsonb,
    is_meaningful BOOLEAN DEFAULT true,
    type TEXT,
    severity TEXT DEFAULT 'medium' CHECK (severity IS NULL OR severity IN ('low', 'medium', 'high')),
    title TEXT,
    description TEXT,
    details JSONB DEFAULT '{}'::jsonb,
    metadata JSONB DEFAULT '{}'::jsonb,
    message TEXT,
    is_read BOOLEAN DEFAULT false,
    is_dismissed BOOLEAN DEFAULT false,
    read BOOLEAN DEFAULT false,
    
    created_at TIMESTAMPTZ DEFAULT now()
);

-- Index for competitor lookups
CREATE INDEX IF NOT EXISTS idx_alerts_competitor_id ON alerts(competitor_id);
CREATE INDEX IF NOT EXISTS idx_alerts_created_at ON alerts(created_at);
CREATE INDEX IF NOT EXISTS idx_alerts_user_id ON alerts(user_id);
CREATE INDEX IF NOT EXISTS idx_alerts_user_read_created ON alerts(user_id, is_read, created_at DESC);

-- ══════════════════════════════════════════════════════════════════════════════
-- HELPER FUNCTIONS
-- ══════════════════════════════════════════════════════════════════════════════

-- Function to increment crawl count atomically
CREATE OR REPLACE FUNCTION increment_crawl_count(user_id UUID)
RETURNS void AS $$
BEGIN
    UPDATE users
    SET crawls_today = crawls_today + 1
    WHERE id = user_id;
END;
$$ LANGUAGE plpgsql;

-- Function to increment manual check count atomically
CREATE OR REPLACE FUNCTION increment_manual_check_count(user_id UUID)
RETURNS void AS $$
BEGIN
    UPDATE users
    SET manual_checks_today = manual_checks_today + 1
    WHERE id = user_id;
END;
$$ LANGUAGE plpgsql;

-- Function to reset daily quotas (can be called by cron)
CREATE OR REPLACE FUNCTION reset_daily_quotas()
RETURNS void AS $$
BEGIN
    UPDATE users
    SET 
        crawls_today = 0,
        manual_checks_today = 0,
        last_quota_reset = now()
    WHERE last_quota_reset < CURRENT_DATE;
END;
$$ LANGUAGE plpgsql;

-- ══════════════════════════════════════════════════════════════════════════════
-- ROW LEVEL SECURITY (RLS)
-- ══════════════════════════════════════════════════════════════════════════════

-- Enable RLS on all tables
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE competitors ENABLE ROW LEVEL SECURITY;
ALTER TABLE snapshots ENABLE ROW LEVEL SECURITY;
ALTER TABLE alerts ENABLE ROW LEVEL SECURITY;

-- Users can only see their own data
CREATE POLICY "Users can view own data" ON users
    FOR SELECT USING (auth.uid() = id);

CREATE POLICY "Users can update own data" ON users
    FOR UPDATE USING (auth.uid() = id);

-- Competitors: users can only access their own
CREATE POLICY "Users can view own competitors" ON competitors
    FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own competitors" ON competitors
    FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own competitors" ON competitors
    FOR UPDATE USING (auth.uid() = user_id);

CREATE POLICY "Users can delete own competitors" ON competitors
    FOR DELETE USING (auth.uid() = user_id);

-- Snapshots: users can view snapshots of their competitors
CREATE POLICY "Users can view own snapshots" ON snapshots
    FOR SELECT USING (
        competitor_id IN (
            SELECT id FROM competitors WHERE user_id = auth.uid()
        )
    );

-- Alerts: users can view alerts for their competitors
CREATE POLICY "Users can view own alerts" ON alerts
    FOR SELECT USING (
        competitor_id IN (
            SELECT id FROM competitors WHERE user_id = auth.uid()
        )
    );

-- ══════════════════════════════════════════════════════════════════════════════
-- SERVICE ROLE BYPASS (for cron jobs and webhooks)
-- ══════════════════════════════════════════════════════════════════════════════

-- Allow service role to bypass RLS for server-side operations
CREATE POLICY "Service role has full access to users" ON users
    FOR ALL USING (auth.jwt() ->> 'role' = 'service_role');

CREATE POLICY "Service role has full access to competitors" ON competitors
    FOR ALL USING (auth.jwt() ->> 'role' = 'service_role');

CREATE POLICY "Service role has full access to snapshots" ON snapshots
    FOR ALL USING (auth.jwt() ->> 'role' = 'service_role');

CREATE POLICY "Service role has full access to alerts" ON alerts
    FOR ALL USING (auth.jwt() ->> 'role' = 'service_role');


-- ====================================================================== --
-- SOURCE: supabase/migrations/20251215_analyses_table.sql
-- ====================================================================== --

-- Analyses Table for Vision-Based Competitor Analysis
-- Run this in Supabase SQL Editor

CREATE TABLE IF NOT EXISTS analyses (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    competitor_id UUID NOT NULL REFERENCES competitors(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    analysis_data JSONB NOT NULL,
    analysis_hash VARCHAR(64) NOT NULL,  -- SHA256 hash of key fields for change detection
    raw_analysis TEXT,
    screenshot_size INTEGER,
    model VARCHAR(100),
    has_changes BOOLEAN DEFAULT FALSE,  -- True if this analysis differs from previous
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Index for fast lookups
CREATE INDEX IF NOT EXISTS idx_analyses_competitor ON analyses(competitor_id);
CREATE INDEX IF NOT EXISTS idx_analyses_user ON analyses(user_id);
CREATE INDEX IF NOT EXISTS idx_analyses_created ON analyses(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_analyses_hash ON analyses(analysis_hash);

-- RLS Policies
ALTER TABLE analyses ENABLE ROW LEVEL SECURITY;

-- Users can read their own analyses
CREATE POLICY "Users can read own analyses"
    ON analyses FOR SELECT
    USING (auth.uid() = user_id);

-- Users can insert their own analyses
CREATE POLICY "Users can insert own analyses"
    ON analyses FOR INSERT
    WITH CHECK (auth.uid() = user_id);

-- Service role can do everything
CREATE POLICY "Service role full access to analyses"
    ON analyses FOR ALL
    USING (auth.role() = 'service_role');



-- ====================================================================== --
-- SOURCE: supabase/migrations/004_user_settings.sql
-- ====================================================================== --

-- Add settings JSONB column to users table
-- Stores user preferences for notifications and integrations

ALTER TABLE users ADD COLUMN IF NOT EXISTS settings JSONB DEFAULT '{
  "email_enabled": true,
  "digest_frequency": "instant",
  "slack_webhook_url": null
}'::jsonb;

-- Add index for querying settings
CREATE INDEX IF NOT EXISTS idx_users_settings ON users USING gin(settings);

-- Comment for documentation
COMMENT ON COLUMN users.settings IS 'User notification preferences: email_enabled, digest_frequency, slack_webhook_url';


-- ====================================================================== --
-- SOURCE: supabase/migrations/20260102_pricing_contexts.sql
-- ====================================================================== --

-- ══════════════════════════════════════════════════════════════════════════════
-- RivalEye Geo-Aware Pricing Schema
-- Migration: 20260102_pricing_contexts
-- ══════════════════════════════════════════════════════════════════════════════

-- ──────────────────────────────────────────────────────────────────────────────
-- 1. PRICING CONTEXTS TABLE
-- ──────────────────────────────────────────────────────────────────────────────
create table if not exists pricing_contexts (
  id uuid primary key default gen_random_uuid(),
  key text unique not null,
  country text,
  currency text,
  locale text not null,
  timezone text not null,
  requires_browser boolean default false,
  created_at timestamptz default now()
);

insert into pricing_contexts (key, country, currency, locale, timezone, requires_browser)
values
  ('us', 'US', 'USD', 'en-US', 'America/New_York', true),
  ('in', 'IN', 'INR', 'en-IN', 'Asia/Kolkata', true),
  ('eu', 'DE', 'EUR', 'en-DE', 'Europe/Berlin', true),
  ('global', null, null, 'en-US', 'UTC', false)
on conflict (key) do nothing;

-- ──────────────────────────────────────────────────────────────────────────────
-- 2. PRICING SNAPSHOTS TABLE
-- ──────────────────────────────────────────────────────────────────────────────
create table if not exists pricing_snapshots (
  id uuid primary key default gen_random_uuid(),
  competitor_id uuid not null references competitors(id) on delete cascade,
  pricing_context_id uuid not null references pricing_contexts(id),
  source text not null check (source in ('firecrawl', 'playwright')),
  currency_detected text,
  pricing_schema jsonb not null,
  dom_hash text,
  screenshot_path text,
  taken_at timestamptz default now()
);

create index if not exists idx_pricing_snapshots_competitor_context 
  on pricing_snapshots (competitor_id, pricing_context_id, taken_at desc);

-- ──────────────────────────────────────────────────────────────────────────────
-- 3. PRICING DIFFS TABLE
-- ──────────────────────────────────────────────────────────────────────────────
create table if not exists pricing_diffs (
  id uuid primary key default gen_random_uuid(),
  competitor_id uuid not null references competitors(id) on delete cascade,
  pricing_context_id uuid not null references pricing_contexts(id),
  snapshot_before_id uuid references pricing_snapshots(id),
  snapshot_after_id uuid not null references pricing_snapshots(id),
  severity numeric not null check (severity >= 0 and severity <= 1),
  diff_type text not null,
  diff jsonb not null,
  summary text not null,
  ai_explanation text,
  is_notified boolean default false,
  created_at timestamptz default now()
);

create index if not exists idx_pricing_diffs_competitor 
  on pricing_diffs (competitor_id, created_at desc);

-- ──────────────────────────────────────────────────────────────────────────────
-- 4. SCREENSHOTS STORAGE BUCKET
-- ──────────────────────────────────────────────────────────────────────────────
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'screenshots',
  'screenshots',
  true,
  5242880,
  array['image/webp', 'image/jpeg', 'image/png']
)
on conflict (id) do nothing;

create policy "Allow service role full access"
  on storage.objects for all
  to service_role
  using (bucket_id = 'screenshots');

create policy "Allow public read"
  on storage.objects for select
  to public
  using (bucket_id = 'screenshots');

-- ──────────────────────────────────────────────────────────────────────────────
-- 5. HELPER FUNCTION
-- ──────────────────────────────────────────────────────────────────────────────
create or replace function get_latest_snapshot(
  p_competitor_id uuid,
  p_context_id uuid
) returns pricing_snapshots as $$
  select *
  from pricing_snapshots
  where competitor_id = p_competitor_id
    and pricing_context_id = p_context_id
  order by taken_at desc
  limit 1;
$$ language sql stable;

-- ──────────────────────────────────────────────────────────────────────────────
-- 6. UPDATE COMPETITORS TABLE
-- ──────────────────────────────────────────────────────────────────────────────
alter table competitors 
  add column if not exists best_scraper text check (best_scraper in ('firecrawl', 'playwright'));


-- ====================================================================== --
-- SOURCE: supabase/migrations/20260103_branding_table.sql
-- ====================================================================== --

-- RivalEye: Branding Extraction Feature Migration
-- Creates table for storing competitor branding/design system data

-- ══════════════════════════════════════════════════════════════════════════════
-- COMPETITOR BRANDING TABLE
-- ══════════════════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS competitor_branding (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    competitor_id UUID NOT NULL REFERENCES competitors(id) ON DELETE CASCADE,
    branding_data JSONB NOT NULL,
    extracted_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Index for efficient lookup by competitor
CREATE INDEX IF NOT EXISTS idx_competitor_branding_competitor 
    ON competitor_branding(competitor_id);

-- Index for ordering by extraction time
CREATE INDEX IF NOT EXISTS idx_competitor_branding_extracted 
    ON competitor_branding(extracted_at DESC);

-- ══════════════════════════════════════════════════════════════════════════════
-- COMMENTS
-- ══════════════════════════════════════════════════════════════════════════════

COMMENT ON TABLE competitor_branding IS 'Stores extracted branding/design system data for competitors (Pro feature)';
COMMENT ON COLUMN competitor_branding.branding_data IS 'JSON containing colors, typography, fonts, component styles, assets';


-- ====================================================================== --
-- SOURCE: supabase/migrations/20260103_performance_table.sql
-- ====================================================================== --

-- RivalEye: Performance Insights Feature Migration
-- Creates table for storing competitor performance/Core Web Vitals data

-- ══════════════════════════════════════════════════════════════════════════════
-- COMPETITOR PERFORMANCE TABLE
-- ══════════════════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS competitor_performance (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    competitor_id UUID NOT NULL REFERENCES competitors(id) ON DELETE CASCADE,
    insights JSONB NOT NULL,      -- Full performance insights object
    extracted_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Index for efficient lookup by competitor
CREATE INDEX IF NOT EXISTS idx_competitor_performance_competitor 
    ON competitor_performance(competitor_id);

-- Index for ordering by extraction time
CREATE INDEX IF NOT EXISTS idx_competitor_performance_extracted 
    ON competitor_performance(extracted_at DESC);

-- ══════════════════════════════════════════════════════════════════════════════
-- COMMENTS
-- ══════════════════════════════════════════════════════════════════════════════

COMMENT ON TABLE competitor_performance IS 'Stores Core Web Vitals and performance metrics for competitors (Pro feature)';
COMMENT ON COLUMN competitor_performance.insights IS 'JSON containing coreWebVitals, metrics, resources, score';


-- ====================================================================== --
-- SOURCE: supabase/migrations/20260103_techstack_table.sql
-- ====================================================================== --

-- RivalEye: Tech Stack Detection Feature Migration
-- Creates table for storing competitor tech stack detection data

-- ══════════════════════════════════════════════════════════════════════════════
-- COMPETITOR TECH STACK TABLE
-- ══════════════════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS competitor_techstack (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    competitor_id UUID NOT NULL REFERENCES competitors(id) ON DELETE CASCADE,
    technologies JSONB NOT NULL,  -- Array of detected technologies
    summary JSONB NOT NULL,       -- Framework, analytics, payments summary
    extracted_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Index for efficient lookup by competitor
CREATE INDEX IF NOT EXISTS idx_competitor_techstack_competitor 
    ON competitor_techstack(competitor_id);

-- Index for ordering by extraction time
CREATE INDEX IF NOT EXISTS idx_competitor_techstack_extracted 
    ON competitor_techstack(extracted_at DESC);

-- ══════════════════════════════════════════════════════════════════════════════
-- COMMENTS
-- ══════════════════════════════════════════════════════════════════════════════

COMMENT ON TABLE competitor_techstack IS 'Stores detected tech stack for competitors (Pro feature)';
COMMENT ON COLUMN competitor_techstack.technologies IS 'Array of {name, category, confidence, evidence}';
COMMENT ON COLUMN competitor_techstack.summary IS 'JSON with framework, analytics, payments, marketing, hosting';


-- ====================================================================== --
-- SOURCE: supabase/migrations/20260107_pricing_snapshots.sql
-- ====================================================================== --

-- ══════════════════════════════════════════════════════════════════════════════
-- PRICING SNAPSHOTS TABLE
-- Stores historical pricing data for trend analysis and market radar
-- ══════════════════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS pricing_snapshots (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    competitor_id UUID NOT NULL REFERENCES competitors(id) ON DELETE CASCADE,
    
    -- Pricing data
    pricing_data JSONB NOT NULL,           -- Full pricing schema
    region TEXT DEFAULT 'global',           -- Region this snapshot is from
    currency TEXT DEFAULT 'USD',            -- Currency code
    
    -- Metadata
    hash TEXT,                              -- Hash for detecting changes
    source TEXT DEFAULT 'vision',           -- 'vision', 'cheerio', 'firecrawl'
    
    created_at TIMESTAMPTZ DEFAULT now()
);

-- Indexes for efficient queries
CREATE INDEX IF NOT EXISTS idx_pricing_snapshots_competitor_id ON pricing_snapshots(competitor_id);
CREATE INDEX IF NOT EXISTS idx_pricing_snapshots_region ON pricing_snapshots(region);
CREATE INDEX IF NOT EXISTS idx_pricing_snapshots_created_at ON pricing_snapshots(created_at);

-- RLS Policy
ALTER TABLE pricing_snapshots ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own pricing snapshots" ON pricing_snapshots
    FOR SELECT USING (
        competitor_id IN (
            SELECT id FROM competitors WHERE user_id = auth.uid()
        )
    );

CREATE POLICY "Service role has full access to pricing_snapshots" ON pricing_snapshots
    FOR ALL USING (auth.jwt() ->> 'role' = 'service_role');


-- ====================================================================== --
-- SOURCE: supabase/migrations/20260607_increment_manual_check_count.sql
-- ====================================================================== --

CREATE OR REPLACE FUNCTION increment_manual_check_count(user_id UUID)
RETURNS void AS $$
BEGIN
    UPDATE users
    SET manual_checks_today = manual_checks_today + 1
    WHERE id = user_id;
END;
$$ LANGUAGE plpgsql;


-- ====================================================================== --
-- SOURCE: supabase/migrations/20260607_schema_alignment.sql
-- ====================================================================== --

-- Align the database with the current application code paths.
-- Safe to run more than once.

-- Users: app supports enterprise plan and JSON settings.
ALTER TABLE users
    DROP CONSTRAINT IF EXISTS users_plan_check,
    ADD CONSTRAINT users_plan_check CHECK (plan IN ('free', 'pro', 'enterprise'));

ALTER TABLE users
    ADD COLUMN IF NOT EXISTS settings JSONB DEFAULT '{
        "email_enabled": true,
        "digest_frequency": "instant",
        "slack_webhook_url": null
    }'::jsonb;

CREATE INDEX IF NOT EXISTS idx_users_settings ON users USING gin(settings);

-- Competitors: scheduled jobs use is_active while user-facing routes use status.
ALTER TABLE competitors
    ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT true,
    ADD COLUMN IF NOT EXISTS best_scraper TEXT;

ALTER TABLE competitors
    DROP CONSTRAINT IF EXISTS competitors_best_scraper_check,
    ADD CONSTRAINT competitors_best_scraper_check
        CHECK (best_scraper IS NULL OR best_scraper IN ('firecrawl', 'playwright'));

CREATE INDEX IF NOT EXISTS idx_competitors_active ON competitors(is_active);

UPDATE competitors
SET is_active = (status = 'active')
WHERE is_active IS NULL;

-- Analyses: manual analysis stores screenshot paths in R2.
ALTER TABLE analyses
    ADD COLUMN IF NOT EXISTS screenshot_path TEXT;

-- Alerts: current dashboard/API/trigger code uses the richer alert shape below.
ALTER TABLE alerts
    ADD COLUMN IF NOT EXISTS diff_summary TEXT DEFAULT '',
    ADD COLUMN IF NOT EXISTS ai_insight JSONB DEFAULT '{}'::jsonb,
    ADD COLUMN IF NOT EXISTS user_id UUID REFERENCES users(id) ON DELETE CASCADE,
    ADD COLUMN IF NOT EXISTS type TEXT,
    ADD COLUMN IF NOT EXISTS severity TEXT DEFAULT 'medium',
    ADD COLUMN IF NOT EXISTS title TEXT,
    ADD COLUMN IF NOT EXISTS description TEXT,
    ADD COLUMN IF NOT EXISTS details JSONB DEFAULT '{}'::jsonb,
    ADD COLUMN IF NOT EXISTS metadata JSONB DEFAULT '{}'::jsonb,
    ADD COLUMN IF NOT EXISTS message TEXT,
    ADD COLUMN IF NOT EXISTS is_read BOOLEAN DEFAULT false,
    ADD COLUMN IF NOT EXISTS is_dismissed BOOLEAN DEFAULT false,
    ADD COLUMN IF NOT EXISTS read BOOLEAN DEFAULT false;

ALTER TABLE alerts
    ALTER COLUMN diff_summary DROP NOT NULL,
    ALTER COLUMN ai_insight DROP NOT NULL,
    ALTER COLUMN diff_summary SET DEFAULT '',
    ALTER COLUMN ai_insight SET DEFAULT '{}'::jsonb;

ALTER TABLE alerts
    DROP CONSTRAINT IF EXISTS alerts_severity_check,
    ADD CONSTRAINT alerts_severity_check
        CHECK (severity IS NULL OR severity IN ('low', 'medium', 'high'));

UPDATE alerts a
SET user_id = c.user_id
FROM competitors c
WHERE a.competitor_id = c.id
  AND a.user_id IS NULL;

UPDATE alerts
SET
    title = COALESCE(title, diff_summary, message, 'Competitor change detected'),
    description = COALESCE(description, diff_summary, message, ''),
    type = COALESCE(type, 'change'),
    is_read = COALESCE(is_read, read, false);

CREATE INDEX IF NOT EXISTS idx_alerts_user_id ON alerts(user_id);
CREATE INDEX IF NOT EXISTS idx_alerts_user_read_created ON alerts(user_id, is_read, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_alerts_competitor_created ON alerts(competitor_id, created_at DESC);

-- Pricing snapshots: keep one canonical geo-aware table shape.
ALTER TABLE pricing_snapshots
    ADD COLUMN IF NOT EXISTS pricing_context_id UUID REFERENCES pricing_contexts(id),
    ADD COLUMN IF NOT EXISTS source TEXT,
    ADD COLUMN IF NOT EXISTS currency_detected TEXT,
    ADD COLUMN IF NOT EXISTS pricing_schema JSONB,
    ADD COLUMN IF NOT EXISTS dom_hash TEXT,
    ADD COLUMN IF NOT EXISTS screenshot_path TEXT,
    ADD COLUMN IF NOT EXISTS taken_at TIMESTAMPTZ DEFAULT now();

-- Legacy columns may exist from the older non-geo schema. Add them as nullable
-- compatibility columns before backfilling so this migration works from either
-- schema shape.
ALTER TABLE pricing_snapshots
    ADD COLUMN IF NOT EXISTS pricing_data JSONB,
    ADD COLUMN IF NOT EXISTS region TEXT,
    ADD COLUMN IF NOT EXISTS currency TEXT,
    ADD COLUMN IF NOT EXISTS hash TEXT,
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT now();

ALTER TABLE pricing_snapshots
    DROP CONSTRAINT IF EXISTS pricing_snapshots_source_check,
    ADD CONSTRAINT pricing_snapshots_source_check
        CHECK (source IS NULL OR source IN ('firecrawl', 'playwright', 'vision', 'cheerio'));

UPDATE pricing_snapshots
SET
    pricing_schema = COALESCE(pricing_schema, pricing_data),
    currency_detected = COALESCE(currency_detected, currency),
    dom_hash = COALESCE(dom_hash, hash),
    taken_at = COALESCE(taken_at, created_at),
    source = COALESCE(source, 'playwright')
WHERE pricing_schema IS NULL
   OR taken_at IS NULL
   OR currency_detected IS NULL
   OR dom_hash IS NULL
   OR source IS NULL;

UPDATE pricing_snapshots ps
SET pricing_context_id = pc.id
FROM pricing_contexts pc
WHERE ps.pricing_context_id IS NULL
  AND pc.key = COALESCE(ps.region, 'global');

UPDATE pricing_snapshots ps
SET pricing_context_id = pc.id
FROM pricing_contexts pc
WHERE ps.pricing_context_id IS NULL
  AND pc.key = 'global';

CREATE INDEX IF NOT EXISTS idx_pricing_snapshots_competitor_taken
    ON pricing_snapshots(competitor_id, taken_at DESC);

CREATE INDEX IF NOT EXISTS idx_pricing_snapshots_context_taken
    ON pricing_snapshots(pricing_context_id, taken_at DESC);

-- Helper functions used by quota code.
CREATE OR REPLACE FUNCTION increment_manual_check_count(user_id UUID)
RETURNS void AS $$
BEGIN
    UPDATE users
    SET manual_checks_today = manual_checks_today + 1
    WHERE id = user_id;
END;
$$ LANGUAGE plpgsql;


-- ====================================================================== --
-- SOURCE: supabase/migrations/20260609_aeo_monitor.sql
-- ====================================================================== --

-- ══════════════════════════════════════════════════════════════════════════════
-- AEO (ANSWER ENGINE OPTIMIZATION) MONITOR
-- Run in Supabase SQL Editor
-- ══════════════════════════════════════════════════════════════════════════════

-- 1. Per-competitor AEO settings
--    Stored on the competitor row (one-to-one) for fast access.
ALTER TABLE competitors
    ADD COLUMN IF NOT EXISTS aeo_queries TEXT[] DEFAULT '{}',
    ADD COLUMN IF NOT EXISTS aeo_industry TEXT,
    ADD COLUMN IF NOT EXISTS aeo_enabled BOOLEAN DEFAULT true;

-- 2. AEO visibility scan results
--    One row per (competitor, query, model, scan).
--    High cardinality but bounded: ~50-250 rows/competitor/day.
CREATE TABLE IF NOT EXISTS aeo_visibility (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    competitor_id UUID NOT NULL REFERENCES competitors(id) ON DELETE CASCADE,

    -- The query we asked (e.g. "best CRM for SaaS startups")
    query TEXT NOT NULL,

    -- Which model answered (chatgpt | perplexity | claude | gemini | google_ai)
    model TEXT NOT NULL CHECK (model IN (
        'chatgpt', 'perplexity', 'claude', 'gemini', 'google_ai'
    )),

    -- Whether the brand was mentioned in the response
    mentioned BOOLEAN NOT NULL,

    -- Position in the response (1 = first mention, null = not mentioned)
    -- For lists, this is the index in the list. For prose, the order of appearance.
    position INTEGER,

    -- The actual response text (truncated to 2KB for storage efficiency)
    response_excerpt TEXT,

    -- Citation URLs the model included (JSON array)
    -- e.g. ["https://stripe.com/pricing", "https://en.wikipedia.org/wiki/Stripe"]
    citations JSONB DEFAULT '[]'::jsonb,

    -- Cost of this individual query (for billing transparency)
    cost_usd NUMERIC(10, 6) DEFAULT 0,

    -- When the scan ran
    scanned_at TIMESTAMPTZ DEFAULT now(),

    -- Latency of the LLM call (ms)
    latency_ms INTEGER
);

-- 3. Indexes for the common queries
--    "Show me this competitor's history" → (competitor_id, scanned_at DESC)
CREATE INDEX IF NOT EXISTS idx_aeo_competitor_time
    ON aeo_visibility(competitor_id, scanned_at DESC);

--    "Show me all queries for this model today" → (model, scanned_at DESC)
CREATE INDEX IF NOT EXISTS idx_aeo_model_time
    ON aeo_visibility(model, scanned_at DESC);

--    "Aggregate visibility score" → (user_id, competitor_id, scanned_at DESC)
CREATE INDEX IF NOT EXISTS idx_aeo_user_competitor_time
    ON aeo_visibility(user_id, competitor_id, scanned_at DESC);

--    "Filter by mentioned=true" → partial index for fast aggregation
CREATE INDEX IF NOT EXISTS idx_aeo_mentioned
    ON aeo_visibility(competitor_id, scanned_at DESC)
    WHERE mentioned = true;

-- 4. Composite view: latest snapshot per (competitor, query, model)
--    This makes dashboard queries O(1) instead of scanning history.
CREATE OR REPLACE VIEW aeo_visibility_latest AS
SELECT DISTINCT ON (competitor_id, query, model)
    id,
    user_id,
    competitor_id,
    query,
    model,
    mentioned,
    position,
    response_excerpt,
    citations,
    cost_usd,
    scanned_at,
    latency_ms
FROM aeo_visibility
ORDER BY competitor_id, query, model, scanned_at DESC;

-- 5. RLS
ALTER TABLE aeo_visibility ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can read their own AEO data"
    ON aeo_visibility FOR SELECT
    USING (auth.uid() = user_id);

CREATE POLICY "Service role can write AEO data"
    ON aeo_visibility FOR INSERT
    WITH CHECK (auth.jwt() ->> 'role' = 'service_role');

CREATE POLICY "Service role can update AEO data"
    ON aeo_visibility FOR UPDATE
    USING (auth.jwt() ->> 'role' = 'service_role');

CREATE POLICY "Service role can delete AEO data"
    ON aeo_visibility FOR DELETE
    USING (auth.jwt() ->> 'role' = 'service_role');

-- 6. Index for time-series aggregations (used by the dashboard chart)
CREATE INDEX IF NOT EXISTS idx_aeo_scanned_at
    ON aeo_visibility(scanned_at DESC);

-- 7. RPC: aggregate visibility score for a competitor over a window
--    Returns: total_queries, mentions, visibility_pct, avg_position
--    Visibility % = (mentions / total) * 100
CREATE OR REPLACE FUNCTION get_competitor_visibility(
    p_competitor_id UUID,
    p_since TIMESTAMPTZ DEFAULT now() - INTERVAL '7 days'
)
RETURNS TABLE (
    total_queries BIGINT,
    mentions BIGINT,
    visibility_pct NUMERIC,
    avg_position NUMERIC
)
LANGUAGE plpgsql
AS $$
BEGIN
    RETURN QUERY
    SELECT
        COUNT(*)::BIGINT AS total_queries,
        COUNT(*) FILTER (WHERE mentioned)::BIGINT AS mentions,
        ROUND(
            (COUNT(*) FILTER (WHERE mentioned)::NUMERIC /
             NULLIF(COUNT(*), 0)::NUMERIC) * 100,
            1
        ) AS visibility_pct,
        ROUND(
            AVG(position) FILTER (WHERE mentioned)::NUMERIC,
            1
        ) AS avg_position
    FROM aeo_visibility
    WHERE competitor_id = p_competitor_id
      AND scanned_at >= p_since;
END;
$$;

-- 8. RPC: per-model breakdown for a competitor
CREATE OR REPLACE FUNCTION get_competitor_visibility_by_model(
    p_competitor_id UUID,
    p_since TIMESTAMPTZ DEFAULT now() - INTERVAL '7 days'
)
RETURNS TABLE (
    model TEXT,
    total_queries BIGINT,
    mentions BIGINT,
    visibility_pct NUMERIC,
    avg_position NUMERIC
)
LANGUAGE plpgsql
AS $$
BEGIN
    RETURN QUERY
    SELECT
        aeo_visibility.model,
        COUNT(*)::BIGINT AS total_queries,
        COUNT(*) FILTER (WHERE aeo_visibility.mentioned)::BIGINT AS mentions,
        ROUND(
            (COUNT(*) FILTER (WHERE aeo_visibility.mentioned)::NUMERIC /
             NULLIF(COUNT(*), 0)::NUMERIC) * 100,
            1
        ) AS visibility_pct,
        ROUND(
            AVG(position) FILTER (WHERE aeo_visibility.mentioned)::NUMERIC,
            1
        ) AS avg_position
    FROM aeo_visibility
    WHERE competitor_id = p_competitor_id
      AND scanned_at >= p_since
    GROUP BY aeo_visibility.model
    ORDER BY aeo_visibility.model;
END;
$$;

-- 9. RPC: detect AEO score changes (for the alert system)
--    Returns competitors whose 7-day visibility changed by ≥10% vs previous 7-day
CREATE OR REPLACE FUNCTION detect_aeo_changes(
    p_user_id UUID,
    p_min_change_pct NUMERIC DEFAULT 10
)
RETURNS TABLE (
    competitor_id UUID,
    competitor_name TEXT,
    current_pct NUMERIC,
    previous_pct NUMERIC,
    change_pct NUMERIC
)
LANGUAGE plpgsql
AS $$
BEGIN
    RETURN QUERY
    WITH current AS (
        SELECT
            c.id,
            c.name,
            ROUND(
                (COUNT(*) FILTER (WHERE av.mentioned)::NUMERIC /
                 NULLIF(COUNT(*), 0)::NUMERIC) * 100,
                1
            ) AS pct
        FROM competitors c
        LEFT JOIN aeo_visibility av ON av.competitor_id = c.id
            AND av.scanned_at >= now() - INTERVAL '7 days'
        WHERE c.user_id = p_user_id
        GROUP BY c.id, c.name
    ),
    previous AS (
        SELECT
            c.id,
            ROUND(
                (COUNT(*) FILTER (WHERE av.mentioned)::NUMERIC /
                 NULLIF(COUNT(*), 0)::NUMERIC) * 100,
                1
            ) AS pct
        FROM competitors c
        LEFT JOIN aeo_visibility av ON av.competitor_id = c.id
            AND av.scanned_at >= now() - INTERVAL '14 days'
            AND av.scanned_at < now() - INTERVAL '7 days'
        WHERE c.user_id = p_user_id
        GROUP BY c.id
    )
    SELECT
        c.id,
        c.name,
        c.pct AS current_pct,
        COALESCE(p.pct, 0) AS previous_pct,
        (c.pct - COALESCE(p.pct, 0)) AS change_pct
    FROM current c
    LEFT JOIN previous p ON p.id = c.id
    WHERE ABS(c.pct - COALESCE(p.pct, 0)) >= p_min_change_pct
    ORDER BY ABS(c.pct - COALESCE(p.pct, 0)) DESC;
END;
$$;


-- ====================================================================== --
-- SOURCE: supabase/migrations/20260609_pgvector_embeddings.sql
-- ====================================================================== --

-- ══════════════════════════════════════════════════════════════════════════════
-- PGVECTOR + COMPETITOR EMBEDDINGS (RAG FEATURE)
-- Run in Supabase SQL Editor
-- ══════════════════════════════════════════════════════════════════════════════

-- 1. Enable the pgvector extension (built-in to Supabase, no extra setup)
CREATE EXTENSION IF NOT EXISTS vector;

-- 2. Embeddings table
--    - One row per analysis (links to competitor_id for ownership scoping)
--    - 1536 dimensions matches OpenAI text-embedding-3-small
--    - Indexed with IVFFlat for fast cosine-similarity search
CREATE TABLE IF NOT EXISTS competitor_embeddings (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    competitor_id UUID NOT NULL REFERENCES competitors(id) ON DELETE CASCADE,
    analysis_id UUID NOT NULL REFERENCES analyses(id) ON DELETE CASCADE,
    content TEXT NOT NULL,                    -- the source text that was embedded
    embedding vector(1536),                  -- the embedding vector
    created_at TIMESTAMPTZ DEFAULT now()
);

-- 3. Indexes for fast lookup
CREATE INDEX IF NOT EXISTS idx_competitor_embeddings_competitor
    ON competitor_embeddings(competitor_id);
CREATE INDEX IF NOT EXISTS idx_competitor_embeddings_user
    ON competitor_embeddings(user_id);
CREATE INDEX IF NOT EXISTS idx_competitor_embeddings_created
    ON competitor_embeddings(created_at DESC);

-- 4. IVFFlat index for fast similarity search
--    NOTE: requires at least ~1000 rows to be effective. For smaller
--    datasets Postgres will fall back to sequential scan which is fine.
--    lists=100 is a good default for <100K rows.
CREATE INDEX IF NOT EXISTS idx_competitor_embeddings_vector
    ON competitor_embeddings
    USING ivfflat (embedding vector_cosine_ops)
    WITH (lists = 100);

-- 5. RPC function: semantic search with user-scope + similarity threshold
--    Returns top N matches filtered by the calling user (RLS-friendly).
CREATE OR REPLACE FUNCTION match_competitor_embeddings(
    query_embedding vector(1536),
    match_user_id UUID,
    match_threshold FLOAT DEFAULT 0.7,
    match_count INT DEFAULT 10
)
RETURNS TABLE (
    id UUID,
    competitor_id UUID,
    analysis_id UUID,
    content TEXT,
    similarity FLOAT
)
LANGUAGE plpgsql
AS $$
BEGIN
    RETURN QUERY
    SELECT
        ce.id,
        ce.competitor_id,
        ce.analysis_id,
        ce.content,
        1 - (ce.embedding <=> query_embedding) AS similarity
    FROM competitor_embeddings ce
    WHERE ce.user_id = match_user_id
      AND 1 - (ce.embedding <=> query_embedding) > match_threshold
    ORDER BY ce.embedding <=> query_embedding
    LIMIT match_count;
END;
$$;

-- 6. Enable RLS
ALTER TABLE competitor_embeddings ENABLE ROW LEVEL SECURITY;

-- 7. RLS policies (same pattern as competitors/alerts)
CREATE POLICY "Users can read their own embeddings"
    ON competitor_embeddings FOR SELECT
    USING (auth.uid() = user_id);

CREATE POLICY "Service role can write embeddings"
    ON competitor_embeddings FOR INSERT
    WITH CHECK (auth.jwt() ->> 'role' = 'service_role');

CREATE POLICY "Service role can delete embeddings"
    ON competitor_embeddings FOR DELETE
    USING (auth.jwt() ->> 'role' = 'service_role');


-- ====================================================================== --
-- SOURCE: supabase/migrations/20260615_public_slug.sql
-- ====================================================================== --

-- SEC-4 / PERF-1: indexed public slug for the /track/[slug] public tracker.
--
-- Before: the public API loaded up to 500 active competitors into memory and
-- did an in-memory hostname match on every request (O(n) scan, leaks scale).
-- After: an indexed `public_slug` column derived from the URL hostname, plus a
-- `public_listed` opt-in flag so exposure can be controlled per row.
--
-- NOTE (product decision): `public_listed` defaults to TRUE to preserve the
-- current "viral wedge" behavior where any tracked competitor is publicly
-- visible. Flip the default (or expose a user toggle) if competitors should be
-- private by default.

ALTER TABLE competitors ADD COLUMN IF NOT EXISTS public_slug TEXT;
ALTER TABLE competitors ADD COLUMN IF NOT EXISTS public_listed BOOLEAN NOT NULL DEFAULT true;

-- Derive slug = hostname with dots → dashes (matches the route's normalization:
-- new URL(url).hostname.replace(/\./g, '-')).
CREATE OR REPLACE FUNCTION competitors_set_public_slug() RETURNS trigger AS $$
BEGIN
  NEW.public_slug := replace(
    lower(
      regexp_replace(
        regexp_replace(NEW.url, '^https?://', '', 'i'), -- strip scheme
        '[/:?#].*$', ''                                 -- strip path/port/query/fragment
      )
    ),
    '.', '-'
  );
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_competitors_public_slug ON competitors;
CREATE TRIGGER trg_competitors_public_slug
  BEFORE INSERT OR UPDATE OF url ON competitors
  FOR EACH ROW EXECUTE FUNCTION competitors_set_public_slug();

-- Backfill existing rows.
UPDATE competitors
SET public_slug = replace(
  lower(regexp_replace(regexp_replace(url, '^https?://', '', 'i'), '[/:?#].*$', '')),
  '.', '-'
)
WHERE public_slug IS NULL;

-- Partial index covering exactly the public lookup predicate.
CREATE INDEX IF NOT EXISTS idx_competitors_public_slug
  ON competitors (public_slug)
  WHERE status = 'active' AND public_listed = true;

