#!/usr/bin/env bash
# Regenerates supabase/bootstrap.sql — a single, ordered, run-once script that
# recreates the entire RivalEye database in a fresh Supabase project.
#
# Order is DEPENDENCY order (not filename order): schema.sql defines the base
# tables every migration builds on, so it must run first; pricing_snapshots
# depends on pricing_contexts; etc. Re-run this script whenever a migration is
# added so bootstrap.sql stays current.
#
# Usage: bash scripts/build-bootstrap.sh
set -euo pipefail
cd "$(dirname "$0")/.."

OUT="supabase/bootstrap.sql"

# Files in strict dependency order.
FILES=(
  "supabase/schema.sql"
  "supabase/migrations/20251215_analyses_table.sql"
  "supabase/migrations/004_user_settings.sql"
  "supabase/migrations/20260102_pricing_contexts.sql"
  "supabase/migrations/20260103_branding_table.sql"
  "supabase/migrations/20260103_performance_table.sql"
  "supabase/migrations/20260103_techstack_table.sql"
  "supabase/migrations/20260107_pricing_snapshots.sql"
  "supabase/migrations/20260607_increment_manual_check_count.sql"
  "supabase/migrations/20260607_schema_alignment.sql"
  "supabase/migrations/20260609_aeo_monitor.sql"
  "supabase/migrations/20260609_pgvector_embeddings.sql"
  "supabase/migrations/20260615_public_slug.sql"
)

{
  echo "-- ============================================================================"
  echo "-- RIVALEYE — BOOTSTRAP (auto-generated by scripts/build-bootstrap.sh)"
  echo "-- Recreates the full database in a FRESH Supabase project."
  echo "--"
  echo "-- HOW TO USE:"
  echo "--   1. Create a new Supabase project."
  echo "--   2. Open SQL Editor → paste this whole file → Run."
  echo "--   3. Enable the 'vector' extension if the CREATE EXTENSION line errors"
  echo "--      (Database → Extensions → enable 'vector'), then re-run from that line."
  echo "--   4. Auth → Providers: enable Email (magic link), Google, GitHub."
  echo "--"
  echo "-- RUN ONCE on a blank project. Some statements use CREATE POLICY (not"
  echo "-- idempotent) and will error if re-run on a populated database."
  echo "-- Generated: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo "-- ============================================================================"
  echo
  for f in "${FILES[@]}"; do
    if [[ ! -f "$f" ]]; then
      echo "ERROR: missing $f" >&2
      exit 1
    fi
    echo
    echo "-- ====================================================================== --"
    echo "-- SOURCE: $f"
    echo "-- ====================================================================== --"
    echo
    cat "$f"
    echo
  done
} > "$OUT"

echo "Wrote $OUT ($(wc -l < "$OUT" | tr -d ' ') lines from ${#FILES[@]} files)"
